feat: 공간 인덱스 작성
map-befine-official/map-befine-official.github.io pull request #18
Opened 2023-10-23 07:21 UTC by cpot5620

이거 올려놓은줄 알았는데... 다 작성해놓고 까먹었네요,,

2023-10-23 07:34 UTC, junpakPark approved these changes
글 잘 읽었습니다 👍

2023-10-23 07:34 UTC, junpakPark commented on contents/posts/spatial-index/index.md
> +**예비군으로 인해, 대신 성능 테스트를 진행해 준 `준팍` 고맙습니다 !**
쥬니 덕분에 공부 했죠 👍

2023-10-24 05:23 UTC, yoondgu approved these changes
잘 읽었습니다 ~~! 이번 글도 술술 잘 읽히네요
근데 딱 하나, 이미지가 깨져서 나와요 😿

2023-11-01 08:22 UTC, kpeel5839 requested changes
쥬니짱 코멘트 너무 늦게 남겨서 미안해요!

그리고 RC 도 미안해버령

그래도 고치는데 얼마 안걸리잖아요!

하하하하하

2023-11-01 08:22 UTC, kpeel5839 commented on contents/posts/spatial-index/.index_image/st_buffer-st_contains.png
내 이미지 갖다 썼네!

2023-11-01 08:22 UTC, kpeel5839 commented on contents/posts/spatial-index/index.md
> +<br> 이때, 미터 혹은 그 이하의 오차 없이 동일한 위치를 선택할 확률은 얼마나 될까요 ?
발표자료 그대로 복붙했다!

대본 공개해라!

2023-11-01 08:22 UTC, kpeel5839 commented on contents/posts/spatial-index/index.md
> +<br> 코드 주석으로도 남겨져 있지만, 일반적인 위/경도 좌표를 저장할 때 쓰이는 값인 `4326`으로 SRID 값을 설정하였습니다.
그러면 모든 메소드가 지구 기준으로 진행되는건가용?

2023-11-01 08:22 UTC, kpeel5839 commented on contents/posts/spatial-index/index.md
> +**성능이 최소 10배 이상 차이 나는 것을 확인할 수 있었습니다.**
쥬니짱 이거 실제 성능지표 넣으려다가 못 넣은거에용?

2023-11-01 08:22 UTC, kpeel5839 commented on contents/posts/spatial-index/index.md
> +<br> `@AutoConfigureTestDatabase(replace = Replace.NONE)`설정을 통해 해결할 수 있습니다.
트라블 슈팅 고생했어요 쥬니짱~~

2023-11-01 08:27 UTC, cpot5620 commented on contents/posts/spatial-index/index.md
> +<br> 코드 주석으로도 남겨져 있지만, 일반적인 위/경도 좌표를 저장할 때 쓰이는 값인 `4326`으로 SRID 값을 설정하였습니다.
ㅇ

2023-11-01 08:30 UTC, cpot5620 commented on contents/posts/spatial-index/index.md
> +<br> 이때, 미터 혹은 그 이하의 오차 없이 동일한 위치를 선택할 확률은 얼마나 될까요 ?
ㅋ

2023-11-01 08:30 UTC, cpot5620 commented on contents/posts/spatial-index/index.md
> +**성능이 최소 10배 이상 차이 나는 것을 확인할 수 있었습니다.**
오 예리한데열 ~! 

반영했슴다

2023-11-01 08:30 UTC, cpot5620 commented on contents/posts/spatial-index/index.md
> +<br> `@AutoConfigureTestDatabase(replace = Replace.NONE)`설정을 통해 해결할 수 있습니다.
YYYYYYYES

2023-11-01 08:34 UTC, merged